workflows:
  ios-workflow:
    name: iOS Build
    environment:
      vars:
        XCODE_WORKSPACE: "TUIKitDemo.xcworkspace"
        XCODE_SCHEME: "TUIKitDemo"
        APP_DIR: "Chat/Chat/Swift/TUIKitDemo"
      xcode: latest
    scripts:
      - name: Install CocoaPods
        script: |
          cd $APP_DIR
          pod install --repo-update
      - name: Build & Export IPA
        script: |
          cd $APP_DIR
          xcodebuild clean archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath build/TUIKitDemo.xcarchive
          xcodebuild -exportArchive \
            -archivePath build/TUIKitDemo.xcarchive \
            -exportPath build \
            -exportOptionsPlist <(echo '<?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
          <key>method</key><string>app-store</string>
          <key>compileBitcode</key><false/>
          </dict>
          </plist>')
    artifacts:
      - $APP_DIR/build/*.ipa
    publishing:
      email:
        recipients:
          - xia15686666659@163.com
